#!/bin/bash

echo "Branch-Naming-Conventions hooks......."

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
BRANCH_REGEX="^(develop|master|((feature|hotfix|fix)\/.+))$"

if [[ ! $BRANCH_NAME =~ $BRANCH_REGEX ]]
then
  echo "Rejected due to branching name."
  echo "Please rename '$BRANCH_NAME' branch."
  echo "Branch can be 'master' or 'develop' or 'feature/your-branch-name' or 'hotfix/your-branch-name' or 'fix/your-branch-name'"
  exit 1
fi

echo "✔ Branch-Naming-Conventions hooks"
